apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_back }}
  labels:
     app: {{ .Values.app_back }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app_back }}
  ports:
    - port      : 3003
      targetPort: {{ .Values.ports.back_in }}
      nodePort: {{ .Values.ports.back_out }}
