apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_front }}
  labels:
     app: {{ .Values.app_front }}
spec:
  selector:
    app: {{ .Values.app_front }}
  ports:
    - protocol  : TCP
      port      : {{ .Values.ports.front_out }}
      targetPort: {{ .Values.ports.front_in }}
