apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todo
spec:
  rules:
  - host: www.todo.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app_front }}
            port:
              number: {{ .Values.ports.front_out }}
  - host: www.todo.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app_back }}
            port:
              number: {{ .Values.ports.back_out }}
