on:
  push:
    branches:
      - master
name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs: 
      TAG: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - run: echo "A release was created."
        if: ${{ steps.release.outputs.releases_created }}
      - run: echo "${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release.outputs.releases_created }}
      # For root level packages: ${{ steps.release.outputs.package-a--tag_name }}
      - run: echo "Release ${{ steps.release.outputs['packages/package-a--tag_name'] }} created for package-a."
        if: ${{ steps.release.outputs['packages/package-a--release_created'] }}
      - name: print release info
        run: |
          echo "release(s) have been generated"
          echo "${{ steps.release.outputs[@] }}"
          array= "${{ steps.release.outputs[*] }}"
          echo ${array[@]}
