name: validate
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited  # do not remove, this executes when someone fixes the PR title
    branches:
      - master

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml

      - name: Validate PR title prefix
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "validating PR title: $title"
          regex="^(fix|feat|chore|refactor|build|ci|docs|revert|style|test)(\([a-zA-Z0-9-]+\))?(!)?: .+"
          if [[ ! $title =~ $regex ]]; then
            echo "::error title=Pull request title does not have the required prefix::Please refer to the [CONTRIBUTING doc](https://pages.github.office.opendns.com/nebula/sfcn/CONTRIBUTING.html#commit-types)"
            exit 1
          fi
  retry:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Setting this to false ensures that all attempts run even if one fails
      max-attempts: 3 # Specify the number of times to retry the job if it fails
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a command
        run: |
          echo "settt"
          slep 30
          echo "SSsettt"
